---
- name: Create compactor systemd service unit
  template:
    src: thanos-compactor.service.j2
    dest: /etc/systemd/system/thanos-compactor.service
    owner: root
    group: root
    mode: 0644
  when:
    - thanos_compactor|bool
  notify: restart thanos-compactor

- name: Ensure thanos-compactor service is enabled
  systemd:
    daemon_reload: yes
    name: thanos-compactor
    enabled: yes
  when:
    - thanos_compactor|bool
  notify: restart thanos-compactor

- name: Check if Service Exists
  stat:
    path: /etc/systemd/system/thanos-compactor.service
  register: service_status
  when:
    - not thanos_compactor
    - thanos_remove_unused|bool

- name: Stop thanos compactor
  systemd:
    name: thanos-compactor
    state: stopped
    enabled: yes
    daemon_reload: yes
  when:
    - not thanos_compactor
    - thanos_remove_unused|bool
    - service_status.stat.exists
    - ansible_service_mgr == 'systemd'

- name: Remove thanos compactor
  file:
    path: /etc/systemd/system/thanos-compactor.service
    state: absent
  when:
    - not thanos_compactor
    - thanos_remove_unused|bool
    - ansible_service_mgr == 'systemd'
