---
- name: Restart sidecar service
  listen:
    - restart thanos
    - restart thanos-sidecar
    - restart thanos bucket
  systemd:
    name: thanos-sidecar
    state: restarted
    daemon_reload: true
  when:
    - thanos_sidecar|bool
    - ansible_service_mgr == 'systemd'

- name: Restart query service
  listen:
    - restart thanos
    - restart thanos-query
  systemd:
    name: thanos-query
    state: restarted
    daemon_reload: true
  when:
    - thanos_query|bool
    - ansible_service_mgr == 'systemd'

- name: Restart store service
  listen:
    - restart thanos
    - restart thanos-store
    - restart thanos bucket
  systemd:
    name: thanos-store
    state: restarted
    daemon_reload: true
  when:
    - thanos_store|bool
    - ansible_service_mgr == 'systemd'

- name: Restart compactor service
  listen:
    - restart thanos
    - restart thanos-compactor
    - restart thanos bucket
  systemd:
    name: thanos-compactor
    state: restarted
    daemon_reload: true
  when:
    - thanos_compactor|bool
    - ansible_service_mgr == 'systemd'
