---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: Ubuntu_Bionic
    image: ubuntu:bionic
  - name: Ubuntu_Xenial
    image: ubuntu:xenial
  - name: Debian_Buster
    image: debian:buster
  - name: Debian_Stretch
    image: debian:stretch
  - name: Debian_Jessie
    image: debian:jessie

provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
